SHOP_ITEMS = [
    # Existing items...
    {"id": "w13", "name": "Broń Franka", "type": "weapon", "weapon_type": "sword", "rarity": "legendary", "stats": {"attack": 20, "defense": 5, "magic": 1, "speed": 3, "health_bonus": 20}, "level_req": 1, "price": 1, "description": "Tani miecz Franka"},
    # Other items...
]